### ISSUE TITLE
would this tagger support mini-batch in the future?

### ISSUE THREAD

**Issue by yuchenlin** [cmusjtuliuyuan/SequenceTagging#1]
Hi Yuan,

Thank you so much for this excellent code! Looking for a pytorch version for so long.

I was wondering if there is any possibility that this tagger supports mini-batch in the future?

Thanks,
Bill

**Comment by cmusjtuliuyuan** [comment]
Yes.
The next step is multi-processing, then is mini-batch.

**Comment by yuchenlin** [comment]
that would be great! 
looking forward to that!
