### ISSUE TITLE
F1 on NER is about 57~58

### ISSUE THREAD

**Issue by yuchenlin** [cmusjtuliuyuan/SequenceTagging#2]
Hi Yuan,

I found that the NER performance of this framework (train:eng.trian test: eng.testa) is like 57-58 (F1).
It seems quite lower than expected (88-91) as reported in (Lample et al, 2016). 

I used all the default parameters (except for the epoch num = 100) and my pretrained embedding is the same as yours (glove.6B.100d.txt).

Is there any reason why?

Thanks,

Bill

**Comment by yuchenlin** [comment]
Sorry, I thought you are reproducing that paper and already use char-level word representation. It turns out that there is no char-level stuff not yet.

**Comment by yuchenlin** [comment]
With the same setting, my performance on POS tagging with the conll2000 dataset is about 70~71. Maybe I miss something important?

**Comment by cmusjtuliuyuan** [comment]
Pull the latest code, run it again.
